### ISSUE TITLE
Fails when using NPM v7

### ISSUE THREAD

**Issue by lynxtaa** [YellowKirby/is-ci-cli#13]
These are my scripts in package.json:

```json
"test": "is-ci \"test:coverage\" \"test:watch\"",
"test:watch": "jest --watch",
"test:coverage": "jest --coverage"
```

Running `npm test` fails in npm v7 (npm@7.4.1,  node@15.5.1):

```sh
$ npm test

> vk-group-tracking-bot@0.6.0 test
> is-ci "test:coverage" "test:watch"

npm ERR! code 1
npm ERR! path /home/lynxtaa/code/vk-group-tracking-bot
npm ERR! command failed
npm ERR! command sh -c is-ci "test:coverage" "test:watch"
```

**Comment by YellowKirby** [comment]
Hmm, it turns out upstream `is-ci` added [their own CLI implementation](https://github.com/watson/is-ci#cli-usage) with the same `bin` name (quite a while ago too, I just never noticed). npm 7 changes which package it's linking the bin to:

With `npm@6`:
```sh
> ls -l ./node_modules/.bin/is-ci
./node_modules/.bin/is-ci -> ../is-ci-cli/cli.js
```

`npm@7`:
```sh
> ls -l ./node_modules/.bin/is-ci
./node_modules/.bin/is-ci -> ../is-ci/bin.js
```

So with npm 7 `is-ci` doesn't end up even running this package anymore. Not sure if there's anything we can do to resolve this other than rename the bin script for this project to avoid the name collision. Might be simpler to just use the upstream `is-ci` CLI directly 🤷‍♀️

**Comment by lynxtaa** [comment]
Thanks,

> Might be simpler to just use the upstream is-ci CLI directly 🤷‍♀️

It seems like their own CLI implementation is not a replacement for your package because it lacks if-else functionality

**Comment by YellowKirby** [comment]
> Maybe rename bin-script to `is-ci-cli` to avoid confusion?

Yeah, I don't mind doing that, it's just a bit unfortunate... but no harm in keeping it functional if people find it useful :)

> It seems like their own CLI implementation is not a direct replacement for your package because it lacks if-else functionality. 

It'd be a little more verbose, but I think you could still get all the same functionality with upstream `is-ci`:

```sh
# Using this package
is-ci-cli test:ci test:local
is-ci-cli test:ci

# Using upstream is-ci bin
is-ci && npm run test:ci; is-ci || npm run test:local
is-ci && npm run test:ci || true
```

`is-ci && npm run test:ci || npm run test:local` has the pitfall of still trying to run `npm run test:local` if the `npm run test:ci` fails for any reason, so I think the syntax above avoids that. As far as I know this should also work in Windows, but I'd have to double-check.

**Comment by lynxtaa** [comment]
Thank you!

**Comment by YellowKirby** [comment]
Thanks for bring up this issue and talking it through 🍻
